### ISSUE TITLE
Update Ubuntu cloud init default network settings

### ISSUE THREAD

**Issue by philnewm** [philnewm/packer-templates#1]
The default cloud-init settings for ubuntu box builds should already work with the default ones from their official vrgant box

```
# This file is generated from information provided by the datasource.  Changes
# to it will not persist across an instance reboot.  To disable cloud-init's
# network configuration capabilities, write a file
# /etc/cloud/cloud.cfg.d/99-disable-network-config.cfg with the following:
# network: {config: disabled}
network:
  ethernets:
    enp0s3:
        dhcp4: true
        dhcp6: true
        match:
          macaddress: 02:c6:f7:1b:46:08
        set-name: enp0s3
  version: 2
```

This needs to get tested.
